version: '3.7'
services:
  nginx_service:
    image: nginx:latest
    ports:
      - '8080:80'
      - '443:443'

  mysql_service:
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: rootpass
      MYSQL_ROOT_PASSWORD: rootpass

networks:
  my_network:
    driver: bridge